[package]
authors = ["Trangar <victor.koenders@gmail.com>"]
edition = "2018"
name = "markov"
version = "0.1.0"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
bincode = "1.2"
zip = "0.5"
rand = "0.7"
time = "0.1"